version: "3.7"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_IDE_CONFIG: serverName=PHPSTORM
      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1
      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
    volumes:
      - ./:/var/www/html:cached

  apache:
    volumes:
      - ./:/var/www/html:cached
